version: "3.7"
services:
    airflow-engine:
        build: .
        container_name: airflow
        #command: tail -f /dev/null
        command: /bin/sh -c "/root/airflow/setup.sh"
        init: true
        ports:
            - "8080:8080"
        environment:
            - PYTHONPATH=/root/airflow/
        env_file:
            - mysql.env
        tty: true
        networks:
            - mynet
        volumes:
            - /var/airflowdata/root/airflow/
networks:
    mynet:
volumes:
    airflowdata:
